name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.2
    - name: Install project
      run: 
        npm install
    - name: Create environment file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_NEXT_PUBLIC_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        envkey_NEXT_PUBLIC_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        envkey_NEXT_PUBLIC_AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        envkey_NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
        envkey_NEXT_PUBLIC_STRIPE_PRODUCT_ID: ${{ secrets.STRIPE_PRODUCT_ID }}
        envkey_NEXT_PUBLIC_STRIPE_SUCCESS_URL: https://app.docmeapp.com/checkout/success/
        envkey_NEXT_PUBLIC_STRIPE_CANCELED_URL: https://app.docmeapp.com/checkout/canceled/
        file_name: .env.local
    - name: Read environment file
      id: env-file
      uses: juliangruber/read-file-action@v1.1.4
      with:
        path: .env.local
    - name: Log environment file
      run: echo "${{ steps.env-file.outputs.content }}"
    - name: Build and export project
      run: 
        npm run build
    - name: Delete 404.html folder (causes error during FTP transfer)
      run:
       cd out && rm 404.html/* && rmdir -p 404.html && cd ..
    - name: ftp-action
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        host: "${{ secrets.FTP_SERVER }}"
        user: "${{ secrets.FTP_USERNAME }}"
        password: "${{ secrets.FTP_PASSWORD }}"
        localDir: "out"
        remoteDir: "DOCme-website"
